name: generate-cred

on:
  # Trigger on merging to master.
  push:
    branches:
      - master
  # As well as every 6 hours.
  schedule:
    - cron: 0 */6 * * *

jobs:
  GenerateCred:
    name: Generate Cred
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: SourceCred Cache
        uses: actions/cache@v1
        with:
          # cred-action uses *workspace*/sourcecred_data as it's SOURCECRED_DIRECTORY. Only store the cache from that.
          path: sourcecred_data/cache
          key: SC_CACHE-${{ hashFiles('**/project.json') }}-${{ github.run_id }}
          restore-keys: |
            SC_CACHE-${{ hashFiles('**/project.json') }}-
            SC_CACHE-
      - name: Run SourceCred
        uses: hammadj/cred-action@master
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          SOURCECRED_DISCORD_TOKEN: ${{ secrets.SOURCECRED_DISCORD_TOKEN }}
          SOURCECRED_INITIATIVES_DIRECTORY: ./initiatives
        with:
          project: "@metagame"
          project-file: project.json
          weights: weights.json
          branch-against: master
          automated: true
